---
apiVersion: v1
kind: Namespace
metadata:
  name: fleet-test
  labels:
    app: csg-ime
    env: test
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: fleet-test
  labels:
    app: nginx
    role: web
spec:
  selector:
    app: nginx
    role: web
  ports:
  - name: web
    port: 8999
    protocol: TCP
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: web-ingress
  namespace: fleet-test
spec:
  rules:
  - host: web.example.com
    http:
      paths:
      - backend:
          service:
            name: web
            port:
              name: web
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Pod
metadata:
  name: fleet-test
  namespace: fleet-test
  labels:
    app: nginx
    role: web
spec:
  containers:
  - name: fleet-test
    image: docker.io/library/nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: web
      containerPort: 80
      protocol: TCP