---
apiVersion: v1
kind: Namespace
metadata:
  name: registry-system
  labels:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry-system
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    targetPort: registry
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  name: registry-ingress
  namespace: registry-system
spec:
  rules:
  - host: registry.example.com
    http:
      paths:
      - backend:
          service:
            name: registry
            port:
              number: 5000
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: registry-system
  labels:
    app: registry
spec:
  containers:
  - name: registry
    image: docker.io/library/registry:2
    imagePullPolicy: IfNotPresent
    ports:
    - name: registry
      containerPort: 5000
      protocol: TCP
