---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    #nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: ca-issuer
  name: transmission-ingress
  namespace: transmission
spec:
  rules:
  - host: transmission.example.com
    http:
      paths:
      - backend:
          service:
            name: transmission
            port:
              name: web
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - transmission.example.com
  secretName: transmission-ingress-cert
